:bulb: Update setup readme
kefranabg/bento-starter-docs pull request #13
Opened 2019-08-14 12:42 UTC by Yexan

Hi,

Here is an update on setup readme to ensure the developer has pushed his firebase modifications before to start Circle CI configuration step.
It might sound obvious but if you forget that step and go directly to the next step, your Circle CI configuration will never work :)

Thanks for your project ! 😊🙏🎉

2019-09-23 15:22 UTC, Yexan commented
@kefranabg Any update or I should close it ?

2019-09-30 07:51 UTC, tbetous commented
Hi @Yexan !

Thanks for your PR. Do not close it, I'll check it this week as soon as possible.

2019-09-30 09:57 UTC, kefranabg commented
@Yexan Sorry for that I've been busy these days 😉 Thanks @tbetous for taking this 👍 

Thanks for your work !

2019-10-06 15:27 UTC, tbetous requested changes

2019-10-06 15:27 UTC, tbetous commented on docs/setup/README.md
> +git commit -m 'Add firebase config'
It is ok for me ! Just change the commit message to be suitable with gitmoji. I have added a suggestion.

2019-10-06 15:27 UTC, tbetous commented on docs/setup/README.md
> +git commit -m 'Add firebase config'
```suggestion
git commit -m ':wrench: Add firebase config'
```

2019-10-17 14:25 UTC, tbetous approved these changes

2019-10-17 14:26 UTC, merged

2019-10-17 14:26 UTC, tbetous commented
Thanks a lot for your contribution !

2019-10-17 14:35 UTC, Yexan commented
You're welcome 😊